In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import streamlit as st
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from xgboost import XGBRegressor

df = pd.read_csv('demanddata_2025.csv')
df

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,IFA_FLOW,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17515,2025-12-31,44,28633,30690,26868,3994,6606,0,22126,0,...,266,-212,912,-345,-145,96,1397,-82,1375,-514
17516,2025-12-31,45,27381,30212,25722,4027,6606,0,22126,0,...,27,-488,831,-432,-254,44,1397,-383,1372,-514
17517,2025-12-31,46,26563,29786,25049,4059,6606,0,22126,0,...,-19,-511,828,-452,-295,38,1368,-402,1370,-514
17518,2025-12-31,47,25481,30558,23955,4115,6606,0,22126,0,...,-1166,-658,622,-452,-383,-431,994,-415,1421,-514
17519,2025-12-31,48,24730,30085,23230,4171,6606,0,22126,0,...,-1319,-666,615,-428,-513,-442,928,-414,1416,-514

In [11]:
# making column names lowercase

df.columns = df.columns.str.lower()
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [13]:
# displaying first 5 rows

df.head(5)

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [15]:
# displaying last 5 rows

df.tail(5)

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow
17515,2025-12-31,44,28633,30690,26868,3994,6606,0,22126,0,...,266,-212,912,-345,-145,96,1397,-82,1375,-514
17516,2025-12-31,45,27381,30212,25722,4027,6606,0,22126,0,...,27,-488,831,-432,-254,44,1397,-383,1372,-514
17517,2025-12-31,46,26563,29786,25049,4059,6606,0,22126,0,...,-19,-511,828,-452,-295,38,1368,-402,1370,-514
17518,2025-12-31,47,25481,30558,23955,4115,6606,0,22126,0,...,-1166,-658,622,-452,-383,-431,994,-415,1421,-514
17519,2025-12-31,48,24730,30085,23230,4171,6606,0,22126,0,...,-1319,-666,615,-428,-513,-442,928,-414,1416,-514

In [17]:
# checking dataframe dimensions

print(f"There are {df.shape[0]} rows")
print(f"There are {df.shape[1]} columns")

There are 17520 rows
There are 22 columns

In [19]:
# viewing all column names

i = 0

for column in df.columns:
    i += 1
    print(f"{i}. {column}")

1. settlement_date
2. settlement_period
3. nd
4. tsd
5. england_wales_demand
6. embedded_wind_generation
7. embedded_wind_capacity
8. embedded_solar_generation
9. embedded_solar_capacity
10. non_bm_stor
11. pump_storage_pumping
12. scottish_transfer
13. ifa_flow
14. ifa2_flow
15. britned_flow
16. moyle_flow
17. east_west_flow
18. nemo_flow
19. nsl_flow
20. eleclink_flow
21. viking_flow
22. greenlink_flow

In [21]:
# inspecting data types

df.dtypes

settlement_date              object
settlement_period             int64
nd                            int64
tsd                           int64
england_wales_demand          int64
embedded_wind_generation      int64
embedded_wind_capacity        int64
embedded_solar_generation     int64
embedded_solar_capacity       int64
non_bm_stor                   int64
pump_storage_pumping          int64
scottish_transfer             int64
ifa_flow                      int64
ifa2_flow                     int64
britned_flow                  int64
moyle_flow                    int64
east_west_flow                int64
nemo_flow                     int64
nsl_flow                      int64
eleclink_flow                 int64
viking_flow                   int64
greenlink_flow                int64
dtype: object

In [23]:
# checking for duplicate rows

df.duplicated().sum()

0

In [25]:
# checking for missing values

df.isna().sum()

settlement_date              0
settlement_period            0
nd                           0
tsd                          0
england_wales_demand         0
embedded_wind_generation     0
embedded_wind_capacity       0
embedded_solar_generation    0
embedded_solar_capacity      0
non_bm_stor                  0
pump_storage_pumping         0
scottish_transfer            0
ifa_flow                     0
ifa2_flow                    0
britned_flow                 0
moyle_flow                   0
east_west_flow               0
nemo_flow                    0
nsl_flow                     0
eleclink_flow                0
viking_flow                  0
greenlink_flow               0
dtype: int64

In [27]:
# converting settlement date to datetime format

df['settlement_date'] = pd.to_datetime(df['settlement_date'])
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [31]:
# creating a timestamp column from settlement date and settlement period

time_offset = pd.to_timedelta((df['settlement_period'] - 1) * 30, unit='m')
df['timestamp'] = df['settlement_date'] + time_offset
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow,timestamp
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1026,1,-232,-386,-558,96,0,241,0,2025-01-01 00:00:00
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1023,1,-124,-282,-564,51,0,262,0,2025-01-01 00:30:00
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-922,1,-119,-384,-205,62,0,414,0,2025-01-01 01:00:00
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-915,0,-119,-334,-193,37,0,423,0,2025-01-01 01:30:00
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-899,0,-119,-363,-622,-282,0,288,0,2025-01-01 02:00:00

In [33]:
# setting the timestamp as index

df.set_index('timestamp', inplace=True)
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,...,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,viking_flow,greenlink_flow
timestamp,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [35]:
# exploring impossible values (e.g. negative demand, wind generation greater than installed capacity)

df[df['england_wales_demand'] < 0]

Empty DataFrame
Columns: [settlement_date, settlement_period, nd, tsd, england_wales_demand, embedded_wind_generation, embedded_wind_capacity, embedded_solar_generation, embedded_solar_capacity, non_bm_stor, pump_storage_pumping, scottish_transfer, ifa_flow, ifa2_flow, britned_flow, moyle_flow, east_west_flow, nemo_flow, nsl_flow, eleclink_flow, viking_flow, greenlink_flow]
Index: []

[0 rows x 22 columns]

In [37]:
df[df['embedded_wind_generation'] > df['embedded_wind_capacity']]

Empty DataFrame
Columns: [settlement_date, settlement_period, nd, tsd, england_wales_demand, embedded_wind_generation, embedded_wind_capacity, embedded_solar_generation, embedded_solar_capacity, non_bm_stor, pump_storage_pumping, scottish_transfer, ifa_flow, ifa2_flow, britned_flow, moyle_flow, east_west_flow, nemo_flow, nsl_flow, eleclink_flow, viking_flow, greenlink_flow]
Index: []

[0 rows x 22 columns]

In [39]:
# extracting day, month, year, hour, minute, quarter and weekday and week number from timestamp

df.reset_index('timestamp', inplace=True)
df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['year'] = df['timestamp'].dt.year
df['hour'] = df['timestamp'].dt.hour
df['minute'] = df['timestamp'].dt.minute
df['quarter'] = df['timestamp'].dt.quarter
df['weekday'] = df['timestamp'].dt.weekday
df['week_number'] = df['timestamp'].dt.isocalendar().week

df.head()

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,viking_flow,greenlink_flow,day,month,year,hour,minute,quarter,weekday,week_number
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,241,0,1,1,2025,0,0,1,2,1
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,262,0,1,1,2025,0,30,1,2,1
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,414,0,1,1,2025,1,0,1,2,1
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,423,0,1,1,2025,1,30,1,2,1
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,288,0,1,1,2025,2,0,1,2,1

In [41]:
# creating a column for name of the day (e.g. if weekday == 0 then Monday, if weekday == 1 then Tuesday etc)

def weekday_to_name(day):
    if day == 0:
        return 'Monday'
    elif day == 1:
        return 'Tuesday'
    elif day == 2:
        return 'Wednesday'
    elif day == 3:
        return 'Thursday'
    elif day == 4:
        return 'Friday'
    elif day == 5:
        return 'Saturday'
    else:
        return 'Sunday'

df['day_of_week'] = df['weekday'].apply(weekday_to_name)

df.head()

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,greenlink_flow,day,month,year,hour,minute,quarter,weekday,week_number,day_of_week
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,0,1,1,2025,0,0,1,2,1,Wednesday
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,0,1,1,2025,0,30,1,2,1,Wednesday
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,0,1,1,2025,1,0,1,2,1,Wednesday
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,0,1,1,2025,1,30,1,2,1,Wednesday
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,0,1,1,2025,2,0,1,2,1,Wednesday

In [43]:
# creating a column to flag weekends

def is_weekend(day):
    if day == 5 or day == 6:
        return True
    else:
        return False

df['is_weekend'] = df['weekday'].apply(is_weekend)

df.head()

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,day,month,year,hour,minute,quarter,weekday,week_number,day_of_week,is_weekend
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,1,1,2025,0,0,1,2,1,Wednesday,False
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,1,1,2025,0,30,1,2,1,Wednesday,False
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,1,1,2025,1,0,1,2,1,Wednesday,False
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,1,1,2025,1,30,1,2,1,Wednesday,False
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,1,1,2025,2,0,1,2,1,Wednesday,False

In [49]:
# creating a column for the morning peak hours (7am to 9am)

def is_morning_peak(hour):
    if hour >= 7 and hour <= 9:
        return True
    else:
        return False

df['is_morning_peak'] = df['hour'].apply(is_morning_peak)

df.head(30)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,year,hour,minute,quarter,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,2025,0,0,1,2,1,Wednesday,False,False,False
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,2025,0,30,1,2,1,Wednesday,False,False,False
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,2025,1,0,1,2,1,Wednesday,False,False,False
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,2025,1,30,1,2,1,Wednesday,False,False,False
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,2025,2,0,1,2,1,Wednesday,False,False,False
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,2025,2,30,1,2,1,Wednesday,False,False,False
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,2025,3,0,1,2,1,Wednesday,False,False,False
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,2025,3,30,1,2,1,Wednesday,False,False,False
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,2025,4,0,1,2,1,Wednesday,False,False,False
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,2025,4,30,1,2,1,Wednesday,False,False,False
10,2025-01-01 05:00:00,2025-01-01,11,17383,23985,16289,4594,6606,0,19270,...,2025,5,0,1,2,1,Wednesday,False,False,False
11,2025-01-01 05:30:00,2025-01-01,12,17609,24064,16498,4457,6606,0,19270,...,2025,5,30,1,2,1,Wednesday,False,False,False
12,2025-01-01 06:00:00,2025-01-01,13,18620,24067,17411,4314,6606,0,19270,...,2025,6,0,1,2,1,Wednesday,False,False,False
13,2025-01-01 06:30:00,2025-01-01,14,18757,23989,17485,4171,6606,0,19270,...,2025,6,30,1,2,1,Wednesday,False,False,False
14,2025-01-01 07:00:00,2025-01-01,15,19371,23563,18095,4254,6606,0,19270,...,2025,7,0,1,2,1,Wednesday,False,True,False
15,2025-01-01 07:30:00,2025-01-01,16,19466,23572,18171,4336,6606,0,19270,...,2025,7,30,1,2,1,Wednesday,False,True,False
16,2025-01-01 08:00:00,2025-01-01,17,20047,23638,18688,4600,6606,0,19270,...,2025,8,0,1,2,1,Wednesday,False,True,False
17,2025-01-01 08:30:00,2025-01-01,18,20771,24373,19399,4864,6606,1,19270,...,2025,8,30,1,2,1,Wednesday,False,True,False
18,2025-01-01 09:00:00,2025-01-01,19,22290,25010,20754,4849,6606,29,19270,...,2025,9,0,1,2,1,Wednesday,False,True,False
19,2025-01-01 09:30:00,2025-01-01,20,23225,25784,21697,4833,6606,117,19270,...,2025,9,30,1,2,1,Wednesday,False,True,False
20,2025-01-01 10:00:00,2025-01-01,21,24685,26796,23023,4715,6606,222,19270,...,2025,10,0,1,2,1,Wednesday,False,False,False
21,2025-01-01 10:30:00,2025-01-01,22,25327,27582,23550,4597,6606,329,19270,...,2025,10,30,1,2,1,Wednesday,False,False,False
22,2025-01-01 11:00:00,2025-01-01,23,26995,29359,25023,4448,6606,377,19270,...,2025,11,0,1,2,1,Wednesday,False,False,False
23,2025-01-01 11:30:00,2025-01-01,24,27723,29852,25618,4298,6606,436,19270,...,2025,11,30,1,2,1,Wednesday,False,False,False
24,2025-01-01 12:00:00,2025-01-01,25,28785,30144,26600,4270,6606,475,19270,...,2025,12,0,1,2,1,Wednesday,False,False,False
25,2025-01-01 12:30:00,2025-01-01,26,29386,30688,27073,4241,6606,476,19270,...,2025,12,30,1,2,1,Wednesday,False,False,False
26,2025-01-01 13:00:00,2025-01-01,27,29865,31056,27517,4007,6606,511,19270,...,2025,13,0,1,2,1,Wednesday,False,False,False
27,2025-01-01 13:30:00,2025-01-01,28,29858,31145,27419,3772,6606,510,19270,...,2025,13,30,1,2,1,Wednesday,False,False,False
28,2025-01-01 14:00:00,2025-01-01,29,29999,31271,27504,3541,6606,353,19270,...,2025,14,0,1,2,1,Wednesday,False,False,False
29,2025-01-01 14:30:00,2025-01-01,30,30406,31648,27807,3310,6606,198,19270,...,2025,14,30,1,2,1,Wednesday,False,False,False

In [53]:
# creating a column for the evening peak hours (16pm to 19pm)

def is_evening_peak(hour):
    if hour >= 16 and hour <= 19:
        return True
    else:
        return False

df['is_evening_peak'] = df['hour'].apply(is_evening_peak)

df.head(50)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,year,hour,minute,quarter,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,2025,0,0,1,2,1,Wednesday,False,False,False
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,2025,0,30,1,2,1,Wednesday,False,False,False
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,2025,1,0,1,2,1,Wednesday,False,False,False
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,2025,1,30,1,2,1,Wednesday,False,False,False
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,2025,2,0,1,2,1,Wednesday,False,False,False
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,2025,2,30,1,2,1,Wednesday,False,False,False
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,2025,3,0,1,2,1,Wednesday,False,False,False
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,2025,3,30,1,2,1,Wednesday,False,False,False
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,2025,4,0,1,2,1,Wednesday,False,False,False
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,2025,4,30,1,2,1,Wednesday,False,False,False
10,2025-01-01 05:00:00,2025-01-01,11,17383,23985,16289,4594,6606,0,19270,...,2025,5,0,1,2,1,Wednesday,False,False,False
11,2025-01-01 05:30:00,2025-01-01,12,17609,24064,16498,4457,6606,0,19270,...,2025,5,30,1,2,1,Wednesday,False,False,False
12,2025-01-01 06:00:00,2025-01-01,13,18620,24067,17411,4314,6606,0,19270,...,2025,6,0,1,2,1,Wednesday,False,False,False
13,2025-01-01 06:30:00,2025-01-01,14,18757,23989,17485,4171,6606,0,19270,...,2025,6,30,1,2,1,Wednesday,False,False,False
14,2025-01-01 07:00:00,2025-01-01,15,19371,23563,18095,4254,6606,0,19270,...,2025,7,0,1,2,1,Wednesday,False,True,False
15,2025-01-01 07:30:00,2025-01-01,16,19466,23572,18171,4336,6606,0,19270,...,2025,7,30,1,2,1,Wednesday,False,True,False
16,2025-01-01 08:00:00,2025-01-01,17,20047,23638,18688,4600,6606,0,19270,...,2025,8,0,1,2,1,Wednesday,False,True,False
17,2025-01-01 08:30:00,2025-01-01,18,20771,24373,19399,4864,6606,1,19270,...,2025,8,30,1,2,1,Wednesday,False,True,False
18,2025-01-01 09:00:00,2025-01-01,19,22290,25010,20754,4849,6606,29,19270,...,2025,9,0,1,2,1,Wednesday,False,True,False
19,2025-01-01 09:30:00,2025-01-01,20,23225,25784,21697,4833,6606,117,19270,...,2025,9,30,1,2,1,Wednesday,False,True,False
20,2025-01-01 10:00:00,2025-01-01,21,24685,26796,23023,4715,6606,222,19270,...,2025,10,0,1,2,1,Wednesday,False,False,False
21,2025-01-01 10:30:00,2025-01-01,22,25327,27582,23550,4597,6606,329,19270,...,2025,10,30,1,2,1,Wednesday,False,False,False
22,2025-01-01 11:00:00,2025-01-01,23,26995,29359,25023,4448,6606,377,19270,...,2025,11,0,1,2,1,Wednesday,False,False,False
23,2025-01-01 11:30:00,2025-01-01,24,27723,29852,25618,4298,6606,436,19270,...,2025,11,30,1,2,1,Wednesday,False,False,False
24,2025-01-01 12:00:00,2025-01-01,25,28785,30144,26600,4270,6606,475,19270,...,2025,12,0,1,2,1,Wednesday,False,False,False
25,2025-01-01 12:30:00,2025-01-01,26,29386,30688,27073,4241,6606,476,19270,...,2025,12,30,1,2,1,Wednesday,False,False,False
26,2025-01-01 13:00:00,2025-01-01,27,29865,31056,27517,4007,6606,511,19270,...,2025,13,0,1,2,1,Wednesday,False,False,False
27,2025-01-01 13:30:00,2025-01-01,28,29858,31145,27419,3772,6606,510,19270,...,2025,13,30,1,2,1,Wednesday,False,False,False
28,2025-01-01 14:00:00,2025-01-01,29,29999,31271,27504,3541,6606,353,19270,...,2025,14,0,1,2,1,Wednesday,False,False,False
29,2025-01-01 14:30:00,2025-01-01,30,30406,31648,27807,3310,6606,198,19270,...,2025,14,30,1,2,1,Wednesday,False,False,False
30,2025-01-01 15:00:00,2025-01-01,31,30780,32235,28104,3140,6606,71,19270,...,2025,15,0,1,2,1,Wednesday,False,False,False
31,2025-01-01 15:30:00,2025-01-01,32,31036,32569,28258,2969,6606,5,19270,...,2025,15,30,1,2,1,Wednesday,False,False,False
32,2025-01-01 16:00:00,2025-01-01,33,32260,33833,29332,2734,6606,0,19270,...,2025,16,0,1,2,1,Wednesday,False,False,True
33,2025-01-01 16:30:00,2025-01-01,34,33636,35226,30573,2499,6606,0,19270,...,2025,16,30,1,2,1,Wednesday,False,False,True
34,2025-01-01 17:00:00,2025-01-01,35,34021,35612,30977,2340,6606,0,19270,...,2025,17,0,1,2,1,Wednesday,False,False,True
35,2025-01-01 17:30:00,2025-01-01,36,34014,35605,31045,2181,6606,0,19270,...,2025,17,30,1,2,1,Wednesday,False,False,True
36,2025-01-01 18:00:00,2025-01-01,37,33569,35157,30715,2081,6606,0,19270,...,2025,18,0,1,2,1,Wednesday,False,False,True
37,2025-01-01 18:30:00,2025-01-01,38,32966,34558,30142,1980,6606,0,19270,...,2025,18,30,1,2,1,Wednesday,False,False,True
38,2025-01-01 19:00:00,2025-01-01,39,32273,33867,29570,1882,6606,0,19270,...,2025,19,0,1,2,1,Wednesday,False,False,True
39,2025-01-01 19:30:00,2025-01-01,40,31660,33255,28965,1783,6606,0,19270,...,2025,19,30,1,2,1,Wednesday,False,False,True
40,2025-01-01 20:00:00,2025-01-01,41,31110,32704,28445,1730,6606,0,19270,...,2025,20,0,1,2,1,Wednesday,False,False,False
41,2025-01-01 20:30:00,2025-01-01,42,29907,31503,27382,1676,6606,0,19270,...,2025,20,30,1,2,1,Wednesday,False,False,False
42,2025-01-01 21:00:00,2025-01-01,43,28916,30510,26484,1631,6606,0,19270,...,2025,21,0,1,2,1,Wednesday,False,False,False
43,2025-01-01 21:30:00,2025-01-01,44,27676,29268,25340,1586,6606,0,19270,...,2025,21,30,1,2,1,Wednesday,False,False,False
44,2025-01-01 22:00:00,2025-01-01,45,26773,28361,24526,1526,6606,0,19270,...,2025,22,0,1,2,1,Wednesday,False,False,False
45,2025-01-01 22:30:00,2025-01-01,46,25523,27087,23266,1466,6606,0,19270,...,2025,22,30,1,2,1,Wednesday,False,False,False
46,2025-01-01 23:00:00,2025-01-01,47,24513,25957,22276,1460,6606,0,19270,...,2025,23,0,1,2,1,Wednesday,False,False,False
47,2025-01-01 23:30:00,2025-01-01,48,23688,25042,21513,1453,6606,0,19272,...,2025,23,30,1,2,1,Wednesday,False,False,False
48,2025-01-02 00:00:00,2025-01-02,1,23560,24740,21449,1512,6606,0,19272,...,2025,0,0,1,3,1,Thursday,False,False,False
49,2025-01-02 00:30:00,2025-01-02,2,24268,25354,22173,1571,6606,0,19272,...,2025,0,30,1,3,1,Thursday,False,False,False

In [55]:
# creating a column for night hours (23pm to 6am)

def night_hours(hour):
    if hour <= 6 or hour == 23:
        return True
    else:
        return False

df['night'] = df['hour'].apply(night_hours)

df.head(50)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,hour,minute,quarter,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,0,0,1,2,1,Wednesday,False,False,False,True
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,0,30,1,2,1,Wednesday,False,False,False,True
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,1,0,1,2,1,Wednesday,False,False,False,True
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,1,30,1,2,1,Wednesday,False,False,False,True
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,2,0,1,2,1,Wednesday,False,False,False,True
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,2,30,1,2,1,Wednesday,False,False,False,True
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,3,0,1,2,1,Wednesday,False,False,False,True
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,3,30,1,2,1,Wednesday,False,False,False,True
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,4,0,1,2,1,Wednesday,False,False,False,True
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,4,30,1,2,1,Wednesday,False,False,False,True
10,2025-01-01 05:00:00,2025-01-01,11,17383,23985,16289,4594,6606,0,19270,...,5,0,1,2,1,Wednesday,False,False,False,True
11,2025-01-01 05:30:00,2025-01-01,12,17609,24064,16498,4457,6606,0,19270,...,5,30,1,2,1,Wednesday,False,False,False,True
12,2025-01-01 06:00:00,2025-01-01,13,18620,24067,17411,4314,6606,0,19270,...,6,0,1,2,1,Wednesday,False,False,False,True
13,2025-01-01 06:30:00,2025-01-01,14,18757,23989,17485,4171,6606,0,19270,...,6,30,1,2,1,Wednesday,False,False,False,True
14,2025-01-01 07:00:00,2025-01-01,15,19371,23563,18095,4254,6606,0,19270,...,7,0,1,2,1,Wednesday,False,True,False,False
15,2025-01-01 07:30:00,2025-01-01,16,19466,23572,18171,4336,6606,0,19270,...,7,30,1,2,1,Wednesday,False,True,False,False
16,2025-01-01 08:00:00,2025-01-01,17,20047,23638,18688,4600,6606,0,19270,...,8,0,1,2,1,Wednesday,False,True,False,False
17,2025-01-01 08:30:00,2025-01-01,18,20771,24373,19399,4864,6606,1,19270,...,8,30,1,2,1,Wednesday,False,True,False,False
18,2025-01-01 09:00:00,2025-01-01,19,22290,25010,20754,4849,6606,29,19270,...,9,0,1,2,1,Wednesday,False,True,False,False
19,2025-01-01 09:30:00,2025-01-01,20,23225,25784,21697,4833,6606,117,19270,...,9,30,1,2,1,Wednesday,False,True,False,False
20,2025-01-01 10:00:00,2025-01-01,21,24685,26796,23023,4715,6606,222,19270,...,10,0,1,2,1,Wednesday,False,False,False,False
21,2025-01-01 10:30:00,2025-01-01,22,25327,27582,23550,4597,6606,329,19270,...,10,30,1,2,1,Wednesday,False,False,False,False
22,2025-01-01 11:00:00,2025-01-01,23,26995,29359,25023,4448,6606,377,19270,...,11,0,1,2,1,Wednesday,False,False,False,False
23,2025-01-01 11:30:00,2025-01-01,24,27723,29852,25618,4298,6606,436,19270,...,11,30,1,2,1,Wednesday,False,False,False,False
24,2025-01-01 12:00:00,2025-01-01,25,28785,30144,26600,4270,6606,475,19270,...,12,0,1,2,1,Wednesday,False,False,False,False
25,2025-01-01 12:30:00,2025-01-01,26,29386,30688,27073,4241,6606,476,19270,...,12,30,1,2,1,Wednesday,False,False,False,False
26,2025-01-01 13:00:00,2025-01-01,27,29865,31056,27517,4007,6606,511,19270,...,13,0,1,2,1,Wednesday,False,False,False,False
27,2025-01-01 13:30:00,2025-01-01,28,29858,31145,27419,3772,6606,510,19270,...,13,30,1,2,1,Wednesday,False,False,False,False
28,2025-01-01 14:00:00,2025-01-01,29,29999,31271,27504,3541,6606,353,19270,...,14,0,1,2,1,Wednesday,False,False,False,False
29,2025-01-01 14:30:00,2025-01-01,30,30406,31648,27807,3310,6606,198,19270,...,14,30,1,2,1,Wednesday,False,False,False,False
30,2025-01-01 15:00:00,2025-01-01,31,30780,32235,28104,3140,6606,71,19270,...,15,0,1,2,1,Wednesday,False,False,False,False
31,2025-01-01 15:30:00,2025-01-01,32,31036,32569,28258,2969,6606,5,19270,...,15,30,1,2,1,Wednesday,False,False,False,False
32,2025-01-01 16:00:00,2025-01-01,33,32260,33833,29332,2734,6606,0,19270,...,16,0,1,2,1,Wednesday,False,False,True,False
33,2025-01-01 16:30:00,2025-01-01,34,33636,35226,30573,2499,6606,0,19270,...,16,30,1,2,1,Wednesday,False,False,True,False
34,2025-01-01 17:00:00,2025-01-01,35,34021,35612,30977,2340,6606,0,19270,...,17,0,1,2,1,Wednesday,False,False,True,False
35,2025-01-01 17:30:00,2025-01-01,36,34014,35605,31045,2181,6606,0,19270,...,17,30,1,2,1,Wednesday,False,False,True,False
36,2025-01-01 18:00:00,2025-01-01,37,33569,35157,30715,2081,6606,0,19270,...,18,0,1,2,1,Wednesday,False,False,True,False
37,2025-01-01 18:30:00,2025-01-01,38,32966,34558,30142,1980,6606,0,19270,...,18,30,1,2,1,Wednesday,False,False,True,False
38,2025-01-01 19:00:00,2025-01-01,39,32273,33867,29570,1882,6606,0,19270,...,19,0,1,2,1,Wednesday,False,False,True,False
39,2025-01-01 19:30:00,2025-01-01,40,31660,33255,28965,1783,6606,0,19270,...,19,30,1,2,1,Wednesday,False,False,True,False
40,2025-01-01 20:00:00,2025-01-01,41,31110,32704,28445,1730,6606,0,19270,...,20,0,1,2,1,Wednesday,False,False,False,False
41,2025-01-01 20:30:00,2025-01-01,42,29907,31503,27382,1676,6606,0,19270,...,20,30,1,2,1,Wednesday,False,False,False,False
42,2025-01-01 21:00:00,2025-01-01,43,28916,30510,26484,1631,6606,0,19270,...,21,0,1,2,1,Wednesday,False,False,False,False
43,2025-01-01 21:30:00,2025-01-01,44,27676,29268,25340,1586,6606,0,19270,...,21,30,1,2,1,Wednesday,False,False,False,False
44,2025-01-01 22:00:00,2025-01-01,45,26773,28361,24526,1526,6606,0,19270,...,22,0,1,2,1,Wednesday,False,False,False,False
45,2025-01-01 22:30:00,2025-01-01,46,25523,27087,23266,1466,6606,0,19270,...,22,30,1,2,1,Wednesday,False,False,False,False
46,2025-01-01 23:00:00,2025-01-01,47,24513,25957,22276,1460,6606,0,19270,...,23,0,1,2,1,Wednesday,False,False,False,True
47,2025-01-01 23:30:00,2025-01-01,48,23688,25042,21513,1453,6606,0,19272,...,23,30,1,2,1,Wednesday,False,False,False,True
48,2025-01-02 00:00:00,2025-01-02,1,23560,24740,21449,1512,6606,0,19272,...,0,0,1,3,1,Thursday,False,False,False,True
49,2025-01-02 00:30:00,2025-01-02,2,24268,25354,22173,1571,6606,0,19272,...,0,30,1,3,1,Thursday,False,False,False,True

In [57]:
# creating a column for lag demand (30 min)

df['lagged_demand_30m'] = df['england_wales_demand'].shift(1)
df.head()

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,minute,quarter,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,0,1,2,1,Wednesday,False,False,False,True,NaN
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,30,1,2,1,Wednesday,False,False,False,True,19918.0
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,0,1,2,1,Wednesday,False,False,False,True,20167.0
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,30,1,2,1,Wednesday,False,False,False,True,20328.0
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,0,1,2,1,Wednesday,False,False,False,True,19460.0

In [59]:
# creating a column for lag demand (1 hour)

df['lagged_demand_1h'] = df['england_wales_demand'].shift(2)
df.head()

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,quarter,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,1,2,1,Wednesday,False,False,False,True,NaN,NaN
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,1,2,1,Wednesday,False,False,False,True,19918.0,NaN
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,1,2,1,Wednesday,False,False,False,True,20167.0,19918.0
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,1,2,1,Wednesday,False,False,False,True,20328.0,20167.0
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,1,2,1,Wednesday,False,False,False,True,19460.0,20328.0

In [65]:
# creating a column for lag demand (24 hours)

df['lagged_demand_24h'] = df['england_wales_demand'].shift(48)
df.head(50)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,weekday,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h,lagged_demand_24h
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,2,1,Wednesday,False,False,False,True,NaN,NaN,NaN
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,2,1,Wednesday,False,False,False,True,19918.0,NaN,NaN
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,2,1,Wednesday,False,False,False,True,20167.0,19918.0,NaN
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,2,1,Wednesday,False,False,False,True,20328.0,20167.0,NaN
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,2,1,Wednesday,False,False,False,True,19460.0,20328.0,NaN
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,2,1,Wednesday,False,False,False,True,18654.0,19460.0,NaN
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,2,1,Wednesday,False,False,False,True,18248.0,18654.0,NaN
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,2,1,Wednesday,False,False,False,True,17855.0,18248.0,NaN
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,2,1,Wednesday,False,False,False,True,17367.0,17855.0,NaN
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,2,1,Wednesday,False,False,False,True,16774.0,17367.0,NaN
10,2025-01-01 05:00:00,2025-01-01,11,17383,23985,16289,4594,6606,0,19270,...,2,1,Wednesday,False,False,False,True,16489.0,16774.0,NaN
11,2025-01-01 05:30:00,2025-01-01,12,17609,24064,16498,4457,6606,0,19270,...,2,1,Wednesday,False,False,False,True,16289.0,16489.0,NaN
12,2025-01-01 06:00:00,2025-01-01,13,18620,24067,17411,4314,6606,0,19270,...,2,1,Wednesday,False,False,False,True,16498.0,16289.0,NaN
13,2025-01-01 06:30:00,2025-01-01,14,18757,23989,17485,4171,6606,0,19270,...,2,1,Wednesday,False,False,False,True,17411.0,16498.0,NaN
14,2025-01-01 07:00:00,2025-01-01,15,19371,23563,18095,4254,6606,0,19270,...,2,1,Wednesday,False,True,False,False,17485.0,17411.0,NaN
15,2025-01-01 07:30:00,2025-01-01,16,19466,23572,18171,4336,6606,0,19270,...,2,1,Wednesday,False,True,False,False,18095.0,17485.0,NaN
16,2025-01-01 08:00:00,2025-01-01,17,20047,23638,18688,4600,6606,0,19270,...,2,1,Wednesday,False,True,False,False,18171.0,18095.0,NaN
17,2025-01-01 08:30:00,2025-01-01,18,20771,24373,19399,4864,6606,1,19270,...,2,1,Wednesday,False,True,False,False,18688.0,18171.0,NaN
18,2025-01-01 09:00:00,2025-01-01,19,22290,25010,20754,4849,6606,29,19270,...,2,1,Wednesday,False,True,False,False,19399.0,18688.0,NaN
19,2025-01-01 09:30:00,2025-01-01,20,23225,25784,21697,4833,6606,117,19270,...,2,1,Wednesday,False,True,False,False,20754.0,19399.0,NaN
20,2025-01-01 10:00:00,2025-01-01,21,24685,26796,23023,4715,6606,222,19270,...,2,1,Wednesday,False,False,False,False,21697.0,20754.0,NaN
21,2025-01-01 10:30:00,2025-01-01,22,25327,27582,23550,4597,6606,329,19270,...,2,1,Wednesday,False,False,False,False,23023.0,21697.0,NaN
22,2025-01-01 11:00:00,2025-01-01,23,26995,29359,25023,4448,6606,377,19270,...,2,1,Wednesday,False,False,False,False,23550.0,23023.0,NaN
23,2025-01-01 11:30:00,2025-01-01,24,27723,29852,25618,4298,6606,436,19270,...,2,1,Wednesday,False,False,False,False,25023.0,23550.0,NaN
24,2025-01-01 12:00:00,2025-01-01,25,28785,30144,26600,4270,6606,475,19270,...,2,1,Wednesday,False,False,False,False,25618.0,25023.0,NaN
25,2025-01-01 12:30:00,2025-01-01,26,29386,30688,27073,4241,6606,476,19270,...,2,1,Wednesday,False,False,False,False,26600.0,25618.0,NaN
26,2025-01-01 13:00:00,2025-01-01,27,29865,31056,27517,4007,6606,511,19270,...,2,1,Wednesday,False,False,False,False,27073.0,26600.0,NaN
27,2025-01-01 13:30:00,2025-01-01,28,29858,31145,27419,3772,6606,510,19270,...,2,1,Wednesday,False,False,False,False,27517.0,27073.0,NaN
28,2025-01-01 14:00:00,2025-01-01,29,29999,31271,27504,3541,6606,353,19270,...,2,1,Wednesday,False,False,False,False,27419.0,27517.0,NaN
29,2025-01-01 14:30:00,2025-01-01,30,30406,31648,27807,3310,6606,198,19270,...,2,1,Wednesday,False,False,False,False,27504.0,27419.0,NaN
30,2025-01-01 15:00:00,2025-01-01,31,30780,32235,28104,3140,6606,71,19270,...,2,1,Wednesday,False,False,False,False,27807.0,27504.0,NaN
31,2025-01-01 15:30:00,2025-01-01,32,31036,32569,28258,2969,6606,5,19270,...,2,1,Wednesday,False,False,False,False,28104.0,27807.0,NaN
32,2025-01-01 16:00:00,2025-01-01,33,32260,33833,29332,2734,6606,0,19270,...,2,1,Wednesday,False,False,True,False,28258.0,28104.0,NaN
33,2025-01-01 16:30:00,2025-01-01,34,33636,35226,30573,2499,6606,0,19270,...,2,1,Wednesday,False,False,True,False,29332.0,28258.0,NaN
34,2025-01-01 17:00:00,2025-01-01,35,34021,35612,30977,2340,6606,0,19270,...,2,1,Wednesday,False,False,True,False,30573.0,29332.0,NaN
35,2025-01-01 17:30:00,2025-01-01,36,34014,35605,31045,2181,6606,0,19270,...,2,1,Wednesday,False,False,True,False,30977.0,30573.0,NaN
36,2025-01-01 18:00:00,2025-01-01,37,33569,35157,30715,2081,6606,0,19270,...,2,1,Wednesday,False,False,True,False,31045.0,30977.0,NaN
37,2025-01-01 18:30:00,2025-01-01,38,32966,34558,30142,1980,6606,0,19270,...,2,1,Wednesday,False,False,True,False,30715.0,31045.0,NaN
38,2025-01-01 19:00:00,2025-01-01,39,32273,33867,29570,1882,6606,0,19270,...,2,1,Wednesday,False,False,True,False,30142.0,30715.0,NaN
39,2025-01-01 19:30:00,2025-01-01,40,31660,33255,28965,1783,6606,0,19270,...,2,1,Wednesday,False,False,True,False,29570.0,30142.0,NaN
40,2025-01-01 20:00:00,2025-01-01,41,31110,32704,28445,1730,6606,0,19270,...,2,1,Wednesday,False,False,False,False,28965.0,29570.0,NaN
41,2025-01-01 20:30:00,2025-01-01,42,29907,31503,27382,1676,6606,0,19270,...,2,1,Wednesday,False,False,False,False,28445.0,28965.0,NaN
42,2025-01-01 21:00:00,2025-01-01,43,28916,30510,26484,1631,6606,0,19270,...,2,1,Wednesday,False,False,False,False,27382.0,28445.0,NaN
43,2025-01-01 21:30:00,2025-01-01,44,27676,29268,25340,1586,6606,0,19270,...,2,1,Wednesday,False,False,False,False,26484.0,27382.0,NaN
44,2025-01-01 22:00:00,2025-01-01,45,26773,28361,24526,1526,6606,0,19270,...,2,1,Wednesday,False,False,False,False,25340.0,26484.0,NaN
45,2025-01-01 22:30:00,2025-01-01,46,25523,27087,23266,1466,6606,0,19270,...,2,1,Wednesday,False,False,False,False,24526.0,25340.0,NaN
46,2025-01-01 23:00:00,2025-01-01,47,24513,25957,22276,1460,6606,0,19270,...,2,1,Wednesday,False,False,False,True,23266.0,24526.0,NaN
47,2025-01-01 23:30:00,2025-01-01,48,23688,25042,21513,1453,6606,0,19272,...,2,1,Wednesday,False,False,False,True,22276.0,23266.0,NaN
48,2025-01-02 00:00:00,2025-01-02,1,23560,24740,21449,1512,6606,0,19272,...,3,1,Thursday,False,False,False,True,21513.0,22276.0,19918.0
49,2025-01-02 00:30:00,2025-01-02,2,24268,25354,22173,1571,6606,0,19272,...,3,1,Thursday,False,False,False,True,21449.0,21513.0,20167.0

In [69]:
# creating a column for rolling mean demand (24 hours)

df['demand_rolling_mean_24h'] = df['england_wales_demand'].rolling(window=48, min_periods=1).mean()
df.head(20)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,week_number,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h,lagged_demand_24h,demand_rolling_mean_24h
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,1,Wednesday,False,False,False,True,NaN,NaN,NaN,19918.000000
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,1,Wednesday,False,False,False,True,19918.0,NaN,NaN,20042.500000
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,1,Wednesday,False,False,False,True,20167.0,19918.0,NaN,20137.666667
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,1,Wednesday,False,False,False,True,20328.0,20167.0,NaN,19968.250000
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,1,Wednesday,False,False,False,True,19460.0,20328.0,NaN,19705.400000
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,1,Wednesday,False,False,False,True,18654.0,19460.0,NaN,19462.500000
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,1,Wednesday,False,False,False,True,18248.0,18654.0,NaN,19232.857143
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,1,Wednesday,False,False,False,True,17855.0,18248.0,NaN,18999.625000
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,1,Wednesday,False,False,False,True,17367.0,17855.0,NaN,18752.333333
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,1,Wednesday,False,False,False,True,16774.0,17367.0,NaN,18526.000000
10,2025-01-01 05:00:00,2025-01-01,11,17383,23985,16289,4594,6606,0,19270,...,1,Wednesday,False,False,False,True,16489.0,16774.0,NaN,18322.636364
11,2025-01-01 05:30:00,2025-01-01,12,17609,24064,16498,4457,6606,0,19270,...,1,Wednesday,False,False,False,True,16289.0,16489.0,NaN,18170.583333
12,2025-01-01 06:00:00,2025-01-01,13,18620,24067,17411,4314,6606,0,19270,...,1,Wednesday,False,False,False,True,16498.0,16289.0,NaN,18112.153846
13,2025-01-01 06:30:00,2025-01-01,14,18757,23989,17485,4171,6606,0,19270,...,1,Wednesday,False,False,False,True,17411.0,16498.0,NaN,18067.357143
14,2025-01-01 07:00:00,2025-01-01,15,19371,23563,18095,4254,6606,0,19270,...,1,Wednesday,False,True,False,False,17485.0,17411.0,NaN,18069.200000
15,2025-01-01 07:30:00,2025-01-01,16,19466,23572,18171,4336,6606,0,19270,...,1,Wednesday,False,True,False,False,18095.0,17485.0,NaN,18075.562500
16,2025-01-01 08:00:00,2025-01-01,17,20047,23638,18688,4600,6606,0,19270,...,1,Wednesday,False,True,False,False,18171.0,18095.0,NaN,18111.588235
17,2025-01-01 08:30:00,2025-01-01,18,20771,24373,19399,4864,6606,1,19270,...,1,Wednesday,False,True,False,False,18688.0,18171.0,NaN,18183.111111
18,2025-01-01 09:00:00,2025-01-01,19,22290,25010,20754,4849,6606,29,19270,...,1,Wednesday,False,True,False,False,19399.0,18688.0,NaN,18318.421053
19,2025-01-01 09:30:00,2025-01-01,20,23225,25784,21697,4833,6606,117,19270,...,1,Wednesday,False,True,False,False,20754.0,19399.0,NaN,18487.350000

In [71]:
# creating a column for renewable generation (wind + solar)

df['renewable_gen'] = df['embedded_wind_generation'] + df['embedded_solar_generation']
df.head(10)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,day_of_week,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h,lagged_demand_24h,demand_rolling_mean_24h,renewable_gen
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,Wednesday,False,False,False,True,NaN,NaN,NaN,19918.000000,5405
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,Wednesday,False,False,False,True,19918.0,NaN,NaN,20042.500000,5358
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,Wednesday,False,False,False,True,20167.0,19918.0,NaN,20137.666667,5237
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,Wednesday,False,False,False,True,20328.0,20167.0,NaN,19968.250000,5115
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,Wednesday,False,False,False,True,19460.0,20328.0,NaN,19705.400000,5080
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,Wednesday,False,False,False,True,18654.0,19460.0,NaN,19462.500000,5044
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,Wednesday,False,False,False,True,18248.0,18654.0,NaN,19232.857143,4972
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,Wednesday,False,False,False,True,17855.0,18248.0,NaN,18999.625000,4900
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,Wednesday,False,False,False,True,17367.0,17855.0,NaN,18752.333333,4815
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,Wednesday,False,False,False,True,16774.0,17367.0,NaN,18526.000000,4730

In [73]:
# creating a column for renewable percentage 

df['renewable_pct'] = df['renewable_gen'] / df['england_wales_demand']
df.head(10)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,is_weekend,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h,lagged_demand_24h,demand_rolling_mean_24h,renewable_gen,renewable_pct
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,False,False,False,True,NaN,NaN,NaN,19918.000000,5405,0.271363
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,False,False,False,True,19918.0,NaN,NaN,20042.500000,5358,0.265682
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,False,False,False,True,20167.0,19918.0,NaN,20137.666667,5237,0.257625
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,False,False,False,True,20328.0,20167.0,NaN,19968.250000,5115,0.262847
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,False,False,False,True,19460.0,20328.0,NaN,19705.400000,5080,0.272328
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,False,False,False,True,18654.0,19460.0,NaN,19462.500000,5044,0.276414
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,False,False,False,True,18248.0,18654.0,NaN,19232.857143,4972,0.278465
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,False,False,False,True,17855.0,18248.0,NaN,18999.625000,4900,0.282144
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,False,False,False,True,17367.0,17855.0,NaN,18752.333333,4815,0.287051
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,False,False,False,True,16774.0,17367.0,NaN,18526.000000,4730,0.286858

In [75]:
# creating a column for net demand

df['net_demand'] = df['england_wales_demand'] - df['renewable_gen']
df.head(10)

,timestamp,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,is_morning_peak,is_evening_peak,night,lagged_demand_30m,lagged_demand_1h,lagged_demand_24h,demand_rolling_mean_24h,renewable_gen,renewable_pct,net_demand
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,False,False,True,NaN,NaN,NaN,19918.000000,5405,0.271363,14513
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,False,False,True,19918.0,NaN,NaN,20042.500000,5358,0.265682,14809
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,False,False,True,20167.0,19918.0,NaN,20137.666667,5237,0.257625,15091
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,False,False,True,20328.0,20167.0,NaN,19968.250000,5115,0.262847,14345
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,False,False,True,19460.0,20328.0,NaN,19705.400000,5080,0.272328,13574
5,2025-01-01 02:30:00,2025-01-01,6,19214,24562,18248,5044,6606,0,19270,...,False,False,True,18654.0,19460.0,NaN,19462.500000,5044,0.276414,13204
6,2025-01-01 03:00:00,2025-01-01,7,18874,24258,17855,4972,6606,0,19270,...,False,False,True,18248.0,18654.0,NaN,19232.857143,4972,0.278465,12883
7,2025-01-01 03:30:00,2025-01-01,8,18448,24015,17367,4900,6606,0,19270,...,False,False,True,17855.0,18248.0,NaN,18999.625000,4900,0.282144,12467
8,2025-01-01 04:00:00,2025-01-01,9,17844,24100,16774,4815,6606,0,19270,...,False,False,True,17367.0,17855.0,NaN,18752.333333,4815,0.287051,11959
9,2025-01-01 04:30:00,2025-01-01,10,17545,23924,16489,4730,6606,0,19270,...,False,False,True,16774.0,17367.0,NaN,18526.000000,4730,0.286858,11759

In [83]:
# can save the modified csv file 

df.head()
df.to_csv('cleaned_demand_data_2025.csv', index=False)
print('CSV filed saved successfully.')

CSV filed saved successfully.